### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by bombcar**
mixed up ARM vs A64

### CODE REVIEW

**Review by repo-alt — APPROVED** [review]
Indeed, I womder why you got no warning while compiling.

**Comment by bombcar** [comment]
> 

because ARM was valid heh

**Comment by repo-alt** [comment]
ARM was valid, but you have 2 identical if clauses, IDE usually catches such cases

**Comment by bombcar** [comment]
I don't know if I have the `Scala` stuff enabled in idea tbh

**Pull request merged**
