### PR TITLE
Fix unhandled side for redstone connection

### PR DESCRIPTION
**Pull request by OneEyeMaker**
Fixed crash caused by redstone connection from bottom of block. Resolves [crash discussed in Discord](https://discord.com/channels/181078474394566657/939305179524792340/1186102154533019648)

### CODE REVIEW

**Review by wkalinin — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Comment by bombcar** [comment]
Build error is 

```
/home/runner/work/OpenComputers/OpenComputers/src/main/scala/li/cil/oc/integration/gregtech/RecipeHandler.scala:97:46: value addCNCRecipe is not a member of gregtech.api.interfaces.internal.IGT_RecipeAdder
```

**Comment by chochem** [comment]
yea addCNCRecipe was deprecated for a while and recently removed in gregtech

**Comment by boubou19** [comment]
Do we support OC outside of the pack?

**Comment by chochem** [comment]
its on 'passive' in the support list

**Comment by miozune** [comment]
I did check mention to CNC recipemap but didn't about CNC RA :exploding_head: 
But did it ever used for anything in the era of GregoriusT?

**Comment by miozune** [comment]
Actually GT compat module is _really_ ancient and doesn't include compat with crucial machines like EBF.
https://github.com/GTNewHorizons/OpenComputers/blob/master/src/main/scala/li/cil/oc/integration/gregtech/RecipeHandler.scala
Also MT script is available for adding recipes.
So I highly doubt that anyone is using it, especially CNC one.

**Comment by repo-alt** [comment]
most of the OC/GT compat is in Computronics, OC integration module is minimal

**Comment by OneEyeMaker** [comment]
I updated ***existing*** recipe handlers to RA2. If there is request to implement other handlers - ping me.
This PR should be checked with current config of OC in GTNH (I didn't tested all recipes myself).

**Comment by Dream-Master** [comment]
we edit recipes via core mod so i guess not much original recipes are needed

**Pull request merged**
