### PR TITLE
Allow debug card to insert huge amounts of items, e.g. to fill infinity chest

### PR DESCRIPTION
**Pull request by repo-alt**
Also increase JVM memory pool in gradle script

### CODE REVIEW

**Comment by boubou19** [comment]
that sounds very interesting: how does that work? you just edit the nbt via the card as usual but you can enter a value above 64?

**Comment by repo-alt** [comment]
No, I just literally insert the stuff in the chest. Previously it was limited by the stack size.

**Comment by boubou19** [comment]
oh ok, so i'll stick to direct nbt edit, i'm more used to it, even if i need to downgrade my lua version. But that looks cool, i'll definitely toy with it when i'll have time

**Comment by repo-alt** [comment]
like this: `component.debug.insertItem("iron_ingot", 2000000000, 0, "", x, y, z, 1)`

**Comment by boubou19** [comment]
i see, you just made me change my mind, way quicker and safer than the nbt edit lol

**Comment by SinTh0r4s** [comment]
Did you try to minimize the additionally required memory a bit? Not that 4GB machines will get into trouble running the dev versions. Also: could you open a PR for this on the ExampleMod? That'd be lovely! Many thanks for figuring the issue out!

**Comment by bombcar** [comment]
> Did you try to minimize the additionally required memory a bit? Not that 4GB machines will get into trouble running the dev versions. Also: could you open a PR for this on the ExampleMod? That'd be lovely! Many thanks for figuring the issue out!

Something is strange because aka just completely ignored those values ….  Let’s make a ticket on ExampleMod

**Comment by bombcar** [comment]
https://github.com/SinTh0r4s/ExampleMod1.7.10/issues/59 For JVM discussion

**Comment by repo-alt** [comment]
> Did you try to minimize the additionally required memory a bit? Not that 4GB machines will get into trouble running the dev versions. Also: could you open a PR for this on the ExampleMod? That'd be lovely! Many thanks for figuring the issue out!

Why would that affect actually _running_ the dev versions? As for compiling, 2G is really not that much... 
I'm not sure what value Example mod should use because Scala is a known memory hog, but most mods should not require that much memory to compile. Also I have no idea why I had the same error in IDEA, but perhaps it got fixed after clearing build cache. (I set both Scala and Java additional memory parameter there)

**Comment by SinTh0r4s** [comment]
> > Did you try to minimize the additionally required memory a bit? Not that 4GB machines will get into trouble running the dev versions. Also: could you open a PR for this on the ExampleMod? That'd be lovely! Many thanks for figuring the issue out!
> 
> Why would that affect actually _running_ the dev versions? As for compiling, 2G is really not that much... I'm not sure what value Example mod should use because Scala is a known memory hog, but most mods should not require that much memory to compile. Also I have no idea why I had the same error in IDEA, but perhaps it got fixed after clearing build cache. (I set both Scala and Java additional memory parameter there)

Is that memory required by the compilers only? It might also be applied to the Gradle wrapper. Will it be applied to the java compiler and scala compiler? Some projects use both and that could add up.

**Comment by repo-alt** [comment]
Those parameters are definitely used to launch gradle wrapper, I have no idea what variables gradle uses to lauch Java and Scala compilers. (I'm neither Java developer, nor a gradle expert, I just found some way to avoid crash on my machine, perhaps correct fix should be different. I found it by rolling back revisions and trying to build. After it started to build I picked apart the revision changes to isolate one affecting the build, it happened to be this variable.)

**Review by bombcar — COMMENTED** [review]
the Xmx Xms changes are fine for now but we will revisit when I have access to a windows box

**Review by mitchej123 — APPROVED** [review]

**Pull request merged**
