### PR TITLE
reworked zh_cn translation

### PR DESCRIPTION
**Pull request by HfSrJun**
The original zh_cn translation has bad quality and many mistakes.
So I renewed it.

### CODE REVIEW

**Review by Kiwi233 — CHANGES_REQUESTED** [review]
感谢你提醒了我们OC手册存在的问题，但是这里是1.7.10整合包，需要考虑的是整体的统一，另外，汉化最终的目的是方便玩家理解。汉化组会在后续对手册进行校对，你的PR不会接受。

**Comment by Dream-Master** [comment]
@HfSrJun any news here ?

**Comment by HfSrJun** [comment]
> @HfSrJun any news here ?

Still under discussion. Some changes on items' name have to be reconsidered.

I had PR the translation of official version to CFPA org(https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/4051), and made some changes based on the review. I will sync the changes later.

**Comment by chochem** [comment]
All translations are now handled in a new coordinated effort at at https://discord.com/channels/181078474394566657/1211323236260778124
please come by there :)

**Pull request closed without merging**
