### PR TITLE
Disable incorrect glNormal calls which caused errors.

### PR DESCRIPTION
**Pull request by mjevans**
This resolves https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12876 for me and likely other users of a similar GPU software / driver stack.  (Linux / Mesa based OpenGL)

This commit is inspired by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12876#issuecomment-1643021358 's post linking https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11975 and https://github.com/kfajdsl/OpenComputers/commit/3cc9cd707f192129cefb902e994fbb87c84743f6

src/main/scala/li/cil/oc/client/renderer/item/ItemRenderer.scala
src/main/scala/li/cil/oc/client/renderer/item/UpgradeRenderer.scala
src/main/scala/li/cil/oc/client/renderer/tileentity/RobotRenderer.scala

I don't know OpenGL or what the correct replacement for these errant lighting methods should be, and agree it would be better for someone that does to provide a patch which updates, rather than removes, this lighting method.

However it is far better to have a mod that works and happens to have cosmetically dark objects, than one which corrupts the GPU rendering state.

### CODE REVIEW

**Comment by repo-alt** [comment]
Disabling normals because of the bug in a linux driver seems to be a bit of an overkill, but it's not like I have a better solution...
Can you attach a screenshot of a robot with the normals disabled?

**Comment by Glease** [comment]
you cannot draw a cone in triangle fan mode with correct normals, as the top vertex needs different normal when drawing different surface. Just ditch these not very useful modes and draw trigs directly.

also preferably use the tessellator to batch the vertexes.

**Comment by repo-alt** [comment]
Oh, it uses triangle fan, indeed

**Comment by mjevans** [comment]
@Glease  It looks like this in a creative test world.

Creatix_non_normal

**Review by combusterf — APPROVED** [review]

**Comment by combusterf** [comment]
Tested and fix confirmed :+1:

**Pull request merged**
