### PR TITLE
Configurator upgrade

### PR DESCRIPTION
**Pull request by repo-alt**
(currently supports EIO conduits)
Fixed forestry item converter, adding empty circuit list to all items
Added inventory_controller.installUpgrade function for robots, to use upgrade containers at runtime
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9600

### CODE REVIEW

**Comment by repo-alt** [comment]
With the new CI checks, looks like I should add more runtime() dependencies, like CoFH, and Chisel...

**Comment by repo-alt** [comment]
New inventory_controller API (Robot only): 

`installUpgrade([slot:number]):boolean -- Swaps the installed upgrade in the slot (1 by default) with the content of the currently selected inventory slot.`
`getUpgradeContainerType(slot:number):string -- get upgrade container type at the given slot.`
`getUpgradeContainerTier(slot:number):number -- get upgrade container tier at the given slot.`

Configurator Upgrade API:
`getConduitConfiguration(side:number, direction: number):table -- Get conduit configuration at side facing direction`
`setItemConduitInputColor(side:number, direction: number, color: string):boolean -- Set conduit input color at side facing direction`
`setItemConduitOutputColor(side:number, direction: number, color: string):boolean -- Set conduit output color at side facing direction`
`setItemConduitOutputPriority(side:number, direction: number, priority: number):boolean -- Set conduit output priority at side facing direction`
`setItemConduitFilter(side:number, direction: number, database: string, dbSlot:number, filterIndex:number, isInput:boolean):boolean -- Set conduit input or output filter at side facing direction`
`setEnderLiquidConduitFilter(side:number, direction:number, fluid:string, blacklist:boolean, isInput:boolean[, filterIndex:number]):boolean -- Set ender liquid conduit filter at side facing direction`
`setEnderLiquidConduitColor(side:number, direction:number, isInput:boolean, color:string):boolean -- Set fluid conduit color at side facing direction`
(Robot only)
`replaceConduitFilter(side:number, direction:number, input:boolean):boolean -- Replace conduit input or output filter at side facing direction with the filter in selected slot`

Configurator may be installed in Adapter, Robot, Drone or Microcontroller. For most of the functions first parameter (side) interpretation depends on host, second (direction within conduit bundle) is always absolute.

**Comment by repo-alt** [comment]
If no one want to review that stuff (which is understandable), perhaps just merge that? (it was tested in SSP)

**Comment by Dream-Master** [comment]
i get no crash

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
